### ISSUE TITLE
ProGuard rules causing issues on consumer apps

### ISSUE THREAD

**Issue by jrgonzalezg** [apl-devs/AppIntro#337]
It seems that at some point between 4.0.0 and 4.1.0 there has been a change on the ProGuard rules for this library that is affecting any app that depends on it. I noticed that the APKs for newer version of my apps were both much bigger and much less obfuscated than before with no obvious reason, and it took me all morning to narrow it down to this library.

The reason seems to be that the ProGuard rules for this library are being completely exported to be included on any consumer apps due to declaring them in consumerProguardRules on AppIntro/library/build.gradle . I do not know the reason for this ProGuard rules but they seem far too many for what consumers may need to preserve. Maybe they could be divided in two parts, one for the compilation of the library and one for consumers by using both the consumerProguardRules (with a much reduced proguard file) and normal proguardFile declarations for the remaining rules.

Also, the last rule on the proguard-project.txt already seems to tell consumers to preserve all of the classes from this library, so i am not sure if any of the other rules there is needed at all for consumers, and maybe even this last rule could be rewritten to include only a minimal set of needed things. Additionally, the proguard-rules.pro file seems to be unused and could be deleted.

**Comment by avluis** [comment]
It also seems folks don't read prior issues before opening a new one: #336

**Comment by jrgonzalezg** [comment]
I spend more than 5 hours due to this and maybe i did a fast search on the issues and i did not look at the closed ones when i published mine, so my bad there. Anyway it is hardly a closed issue or one to mark as resolved when there is no new version published without the problem and no big bold letters on the front page warning that this big problem exists and that it totally breaks several app security assumptions.

It is also funny that you talk about people not carefully looking at things when you did commit that rules without thinking much about their awful implications, but i do not want to start a war here, i only wanted to contribute and try to avoid the problem to spend further and affect more apps that it may be affecting already.

**Comment by avluis** [comment]
What war? This is GitHub...

**Comment by jrgonzalezg** [comment]
You really don't see the huge problem with committing that rules? Or with closing the issues related to it while the main page points to use version 4.1.0 when it virally injects wrong ProGuard rules on consumer apps? Or with suggesting to provide PR for issues that are unsolved and undiscussed but closed despite of that? It seems we have pretty different ideas about what the proper constructive way of behaving in GitHub is.

**Comment by avluis** [comment]
If you can do better, go right ahead -- platform is open, no one is holding you back.
But you rather throw insults instead.

**Comment by jrgonzalezg** [comment]
Were are my insults? I have only said things about the issue and the way of handling it and nothing about you but i am sorry if you felt offended on any way. I just think that the issue is very important and it felt like a mistake that you initially disregarded it by simply closing it and telling me i should have seen another closed issue before posting this one.

So thanks for reopening the issue, i really think it will be helpful for other people being able to easily find it on the issue search until a fixed version gets published (since closed issues do not show by default on a search on GitHub).

As for the better fix, i tried to be helpful by doing the analysis at the beginning of the issue, but i do not know the internals of the library, so i expected at least some comment from an author to know why the ProGuard rules were included or what issues were they intended to solve to try to figure out what was needed and what not.

I have looked at your referenced PR, and i see that you reduced the rules to just keep all the classes on the library but not everything else. It may be possible to reduce the kept code even further by analyzing the use cases leading to their inclusion, but i think the changes in your PR are already good enough for a first fix to publish a 4.1.1 version of the library.

Is that PR going to be merged soon? If not, i think the best approach is to extract it to a separate PR and merge that to publish a new version. If you prefer that i do the PR for that i can do it but i think it will be incomplete unless it goes together with a new published version and an updated README.md to try to mitigate the propagation as soon as possible. Therefore, i think it is best if it is done by someone with access to publishing new versions on Maven Central. Do you have access for that?

**Comment by avluis** [comment]
Pushed a commit addressing current proguard issue.

**Comment by peterhav** [comment]
Same issue encountered. Also spend several hours to find out that the update to 4.1.0 in this lib caused the issue :(
An update solving this issue would be very welcome.

**Comment by jrgonzalezg** [comment]
I was under the impression that a closed issue was either a fixed issue or one that won't be accepted / fixed. But here "closed" must have a different meaning, because if you follow the instructions to use this library you introduce problems in your apps and that is still the case since the last published version (and the one mentioned on the README.md) is still the same. So here "closed" is not fixed, because the issue persists. On the other hand, some work has been done on modifying the proguard rules that may lead to a "fix" on the future by publishing a new version. So here "closed" is also not a "won't fix" statement...

**Comment by Andrew-Quebe** [comment]
@jrgonzalezg I was also under the impression that @avluis made a commit that addressed this issue, therefore justifying its closure. 

I realize you want this fixed as soon as possible, but understand that myself and @avluis don't have access to the maven repo that allows library updates. That is why we pool together a bunch of improvements, and submit them to @paolorotolo so he can make an official release.

I'll add this to the 4.2.0 milestone, but above that, there isn't anything I can do to fix it right now. If it's a really big deal, you can always modify the source yourself by cloning the repo, and editing the library files as you wish. If you'd like your name listed as a contributor, you can make a PR with your changes, which will help us greatly. Until then, your patience is appreciated. 

Also note, I close issues automatically that haven't been updated for a while (this one being over a month...that's plenty of time for you to make contributions if the issue was that major). This helps the issues list be small and sorted, so that we don't forget about things and make even more people upset.

**Comment by Andrew-Quebe** [comment]
@jrgonzalezg there...now that it is open again, feel free to list exactly what needs to be done that bf1fb7d4e83d6743e4e74e9c9b30a78de248aa60 didn't address.

**Comment by avluis** [comment]
Will it make you feel any better to know that an update is coming and that you should definitely get it or if you simply want to get it now, make use of [JitPack](https://jitpack.io/#paolorotolo/AppIntro/-SNAPSHOT).
If you don't agree with how things are ran in a particular GitHub repo then I suggest not wording your critique as you did above -- after all, they look more like rants that get people nowhere.
Help improve things not by fighting with the folks maintaining the library but by helping them see things in the way you think would be better.

**Comment by Andrew-Quebe** [comment]
@jrgonzalezg ^^ that too. We, as the maintainers, are doing this in our free time...I can't speak for @avluis, but I apologize if I don't meet your needs exactly, but understand that I maintain this library along with working two jobs, going to college, and having a personal life that doesn't involve a computer sitting in front of me.

**Comment by jrgonzalezg** [comment]
Sorry for the misunderstanding, but i do not have currently any problem or any need for a fix. That is not the issue since i am using a local build published to an internal maven repo. And i have done that from the very beginning so my intention with the issue was not to help myself but to help other users and to help the library not to get a bad reputation due to its effect on apps.

The problem is that new and updating users like me before narrowing the cause to this library, peterhav from previous comments, or several persons i recommended the library that i have had to contact again afterwards (plus probably many more) could still be having the issue and what is worse they could have it unknowingly or be unable to determine the cause. And if there is no warning on the instructions or a published fixed version it will continue to spread with all the implications previously discussed.

So, answering your question what i would have liked to see done was a new version published soon after the problem was discovered. The reason is that the effects of including it as it is on 4.1.0 (especially the deobfuscation part) are a serious business concern for several apps.

On the previous discussion i also thought we have agreed that since the motivating concerns still hold, it was good to at least leave the issue open until @paolorotolo was able to publish a new artifact to Maven Central. It will not fix the spread but at least people that notice the problems will be able to find the cause on the open issues and know that it still occurs and how it could be fixed and avoid submitting a new one (like i did with this #337 due to #336 being closed).

But i totally agree that it is your library and you are the ones to decide how to handle it. My last comment was merely a conceptual curiosity about the meaning you use for "closed" or the policies you follow (that you have now partially described), since the status of the issue changed again while the reasons it was opened haven't changed and there were no additional comments in the discussion.

**Comment by Andrew-Quebe** [comment]
@jrgonzalezg Ok..so here's the dealio. #326 is a pull request that @avluis made which included bf1fb7d4e83d6743e4e74e9c9b30a78de248aa60, however, #326 also contains several improvements to the sample app. 

In a different issue, ([here](https://github.com/paolorotolo/AppIntro/issues/317#issuecomment-259411078), @avluis and I discussed that, while his improvements were good, some changes needed to be made.

I had some free time, and decided to work on the Sample app for a bit, effectively making #326 conflict because I was adding stuff without merging that pull request first. Then the two forks (mine and @avluis's) became uneven, and so I closed #326. What I didn't realize, was that it included bf1fb7d4e83d6743e4e74e9c9b30a78de248aa60 which needed to be kept so as to close this issue.

This is my fault, and I apologize for making everything so confusing, and a little bit disorderly. What I intend to do is remake bf1fb7d4e83d6743e4e74e9c9b30a78de248aa60 myself, or have @avluis make another commit (I don't care either way), and I'll ensure it gets pushed directly to the master branch so that 4.2.0 fixes this issue.

To be perfectly honest, I don't use ProGuard, so your original question didn't really make sense to me, and as such, I kind of ignored it until recently. Thanks for bringing this to our attention.

**Comment by jrgonzalezg** [comment]
Thanks, i saw that the commit is merged and just pending a publication to maven central :)

**Comment by Andrew-Quebe** [comment]
Finally going to close this since it is apparent that these commits have been merged and a maven release will be out in a couple days.

**Comment by jrgonzalezg** [comment]
Has anything blocked the maven release? It seems it was not done after all.
