### ISSUE TITLE
Set custom TypeFace not working.

### ISSUE THREAD

**Issue by pedrohba** [apl-devs/AppIntro#406]
**AppIntro Version**: 4.1.0

**Device/Android Version**: 19+

**Issue details / Repro steps / Use case background**: When we create a new AppIntroFragment with newInstance method and pass the TypeFace as one of the paremeters, the TypeFace passed to newInstance method is not applied to text views.

**Your Code**: ` addSlide(AppIntroFragment.newInstance("My title.", "fonts/Roboto-Light.ttf",
                "My description.", "fonts/Roboto-Light.ttf",
                R.mipmap.my_drawable,
                ContextCompat.getColor(this, R.color.colorPrimary)));`

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

Set custom type face with AppIntroFragment.newInstance not working.

I found the error, it is on line 89 and 98 of the class AppIntroBaseFragment.

`if (titleTypeface != null && titleTypeface.equals(""))`

`if (descTypeface != null && descTypeface.equals(""))`

The condition `titleTypeface.equals("")` and `descTypeface.equals("")` not being denied.

I hope this issue is corrected soon.
Thanks!

**Comment by avluis** [comment]
Where is your code? What are we correcting? What is the issue?

**Comment by pedrohba** [comment]
Sorry! 
Post updated.

**Comment by avluis** [comment]
OK -- so here is the thing.
The issue is not the typeface code itself, but rather how you are using it.
Unfortunately, the sample we had is being reworked into the new example app so it is not in the current revision of the repo.
But this is GitHub so that's not really an issue.

In order to properly implement typefaces, check out [this sample activity](https://github.com/apl-devs/AppIntro/blob/726261aa421a8a27b005b8f078b3f8a0aba8fe79/example/src/main/java/com/github/paolorotolo/appintroexample/CustomTypefaceActivity.java) along [with the strings](https://github.com/apl-devs/AppIntro/blob/726261aa421a8a27b005b8f078b3f8a0aba8fe79/example/src/main/res/values/strings.xml) that it is referencing.

Please let me know if anything needs clarification.
