### ISSUE TITLE
I can't obfuscate my code by using proguard after integrate your library

### ISSUE THREAD

**Issue by KevinYaoooooo** [apl-devs/AppIntro#417]
I can't obfuscate my code by using proguard after integrate your library

**Comment by avluis** [comment]
Please follow the template provided -- that's not something we wrote for giggles.

In regards to your issue, there is a fix already merged with the repo but not yet distributed on gradle -- in order to make use of said fix, you would need to make use of JitPack to grab the latest snapshot build.
Please follow [this link](https://jitpack.io/#paolorotolo/AppIntro/-SNAPSHOT) in order to do so.

On another note, this issue has already been brought up before -- so please make use of the search facility provided on GitHub before creating new issues on any public repo.

@Andrew-Quebe Please keep this open for now for visibility and until next AppIntro push.

**Comment by drdla49** [comment]
Please when you release new version with enale proguard? No snapshot, but stable version. Thank you.

**Comment by avluis** [comment]
New version is up @drdla49 time to update sir~
@KevinYaoooooo You haven't responded in a while, I will assume issue has been fixed.
Please reopen this if this is not the case with some sort of update or issue.
