### ISSUE TITLE
how to set image size in AddSlide(Appintro.AppIntroFragment.NewInstance) in xamarin

### ISSUE THREAD

**Issue by AdEel3286** [apl-devs/AppIntro#431]
AddSlide(AppIntro.AppIntroFragment.NewInstance("Page 1",
                "Page 1",
                Resource.Drawable.App1,
                Color.ParseColor("#51E2B7")));

how can i set the Resource.Drawable.App1 size.
i am using AppIntro v1.0.0 and want to make app intro slides like google photos etc.
 is there any way to adjust the width and height of drawable image in your code for betterment or can u suggest any other way ?

**Comment by johnjake** [comment]
If you wanted to resize the Image App1 this need to be inside a layout (Fragment) you can set the image as BackGround image or you can simply add <ImageView> then specify your image Height and Width. then in your AddSlide used Fragment AddSlide(fragment)

**Comment by avluis** [comment]
I can't help you much with Xamarin, but if your images need manipulation before you can create your fragments, then you need to create a layout first or create an `ImageView` instance via code and attach it to a fragment programmatically.

Closing this for now since this is an edge case. Please reopen if you require further assistance.
