### ISSUE TITLE
Status Bar not colored/hidden

### ISSUE THREAD

**Issue by MarvinAch** [apl-devs/AppIntro#434]
I've tried to use it, it work's fine, but the Status Bar is only White... I cannot imagine that this is normal...

(Latest AppIntro Version, tested on Galaxy S7 Edge on Android 7.0)

```
public class IntroActivity extends AppIntro2 {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
		
        addSlide(AppIntroFragment.newInstance("Welcome!", "This is a demo of the AppIntro library.", R.mipmap.ic_launcher, Color.parseColor("#1976D2")));
        addSlide(AppIntroFragment.newInstance("Clean App Intros", "This library offers developers the ability to add clean app intros at the start of their apps.", R.mipmap.ic_launcher, Color.parseColor("#1976D2")));
        addSlide(AppIntroFragment.newInstance("Simple, yet Customizable", "The library offers a lot of customization, while keeping it simple for those that like simple.", R.mipmap.ic_launcher, Color.parseColor("#1976D2")));
        addSlide(AppIntroFragment.newInstance("Explore", "Feel free to explore the rest of the library demo!", R.mipmap.ic_launcher, Color.parseColor("#1976D2")));
		
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        finish();
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        finish();
    }
}
```

**Comment by MarvinAch** [comment]
![screenshot_20170409-183404](https://cloud.githubusercontent.com/assets/21000019/24839056/25e75048-1d54-11e7-9de9-a9373a74bc1f.png)

**Comment by avluis** [comment]
This is not an AppIntro issue -- please check/post your theme files.
If you are not applying a theme to your App then I would move on to checking styles.

**Comment by Andrew-Quebe** [comment]
Ensure your theme files don't change the status bar color.

**Comment by MarvinAch** [comment]
Ok, my mistake. Now the StatusBar is Black. But how i can i hide it?

**Comment by avluis** [comment]
@MarvinAch It seems [Google](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=android+hide+status+bar) knows the answer to that one.

Even the [Android](https://developer.android.com/training/system-ui/status.html) website has it~

For questions like these, you want to give stackoverflow a check, since your device may limit you here from what we have available to test with.
Here is a Google query that restricts results to stackoverflow.com:
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=site:stackoverflow.com+android+hide+status+bar

**Comment by MarvinAch** [comment]
Ah, ok. I thought AppIntro automatically do this, again my mistake. Sorry :-)
